Name: "Build Godot"
description: "Build a Godot project for multiple platforms"
author: pirey0
inputs:
  name:
    description: 'Name of the exported binary'
    required: true
  preset:
    description: 'Name of the preset in `export_presets.cfg` to use'
    required: true
  subdirectory:
    description: 'Optional name of the subdirectory to put exported project in'
    default: ""
  package:
    description: 'Set true to output an artifact zip file'
    default: false
  projectDir:
    description: 'Location of Godot project in repository'
    default: "."
  debugMode:
    description: 'Whether or not to use `--export-debug`'
    default: false
  editorPath:
    description: 'Path to the godot editor'
    default: ""
    required: true
  templatesDir:
    description: 'Path in repository to folder containing export templates'
    default: ""
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.name }}
    - ${{ inputs.preset }}
    - ${{ inputs.subdirectory }}
    - ${{ inputs.package }}
    - ${{ inputs.projectDir }}
    - ${{ inputs.debugMode }}
    - ${{ inputs.editorPath }}
    - ${{ inputs.templatesDir }}
branding:
  icon: loader
  color: blue