Name: "Build Godot"
description: "Build a Godot project for multiple platforms"
author: pirey0
inputs:
  commands:
    description: 'Commands'
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.commands }}
branding:
  icon: loader
  color: blue