name: Build Test Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Build
        id: build
        uses: pirey0/godot-ci@main
        with:
          commands: |
            chmod +x test/pipeline/action.sh
            test/pipeline/action.sh

      - name: Upload Log Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
      
      - name: Uplaod to Steam development branch
        if: success()
        uses: game-ci/steam-deploy@v3
        with:
           username: ${{ secrets.STEAM_USERNAME }}          
           configVdf: ${{ secrets.STEAM_CONFIG_VDF}}          
           appId: 1234560
           buildDescription: v1.2.3
           rootPath: build
           depot1Path: StandaloneWindows64
           depot1InstallScriptPath: StandaloneWindows64/install_script.vdf
           depot2Path: StandaloneLinux64
           releaseBranch: prerelease

      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[
            {
              "title": "Build ${{ matrix.platform }} - ${{ job.status }}",
              "description": "The build for platform ${{ matrix.platform }} has ${{ job.status }}.",
              "color": "${{ 3066993}}"
            }
          ]'
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: ''
          

#TODO next
#create artifact with build log instead of full build
#find correct build number by looking at tags
#fix steam deployment