name: Build Test Project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Build
        id: build
        uses: pirey0/godot-ci@main
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "true"
          editorPath: test/engine/editor.x86_64
          projectDir: test/project/
          templatesDir: test/engine/export_templates/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
      
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[
            {
              "title": "Build ${{ matrix.platform }} - ${{ job.status }}",
              "description": "The build for platform ${{ matrix.platform }} has ${{ job.status }}.",
              "color": ${{ 3066993}},
            }
          ]'
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: ''
          

#TODO next
#add steam upload
#https://github.com/game-ci/steam-deploy
#improve discord notifier