name: Build Test Project

on: workflow_dispatch

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
      - name: Build
        id: build
        uses: pirey0/godot-ci@main
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "true"
          editorPath: test/engine/editor.x86_64
          projectDir: test/project/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}