name: Discord Test

on: workflow_dispatch

jobs:
  DiscordNotify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} sends its regards.'