name: Update GitHub Secret with .context

on:
  workflow_dispatch:

jobs:
  update-secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read the current secret value
        id: read_secret
        run: |
          secret_value=$(gh secret view CONTEXT_FILE_SECRET --json value -q .value || echo "")
          echo "SECRET_VALUE=${secret_value}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_UPDATER_PAT }}

      - name: Create or update .context file
        run: |
          if [ -z "${{ env.SECRET_VALUE }}" ]; then
            echo "Creating default .context file"
            echo "G_LAST_VERSION=1" > .context
            echo "G_INCR_VERSION=1" >> .context
            echo "G_LAST_SHA=unknown" >> .context
            echo "G_LAST_BRANCH=main" >> .context
          else
            echo "Writing existing secret to .context file"
            echo "${{ env.SECRET_VALUE }}" > .context
          fi

      - name: Update GitHub secret
        run: |
          # Read the content of .context
          context_content=$(cat .context)
          
          # Update the secret with the new content
          gh secret set CONTEXT_FILE_SECRET -b "$context_content"
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_UPDATER_PAT }}