name: Update GitHub Secret with .context

on:
  workflow_dispatch:

jobs:
  update-secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create default .context file if not present
        run: |
          if [ ! -f .context ]; then
            echo "G_LAST_VERSION=1" > .context
            echo "G_INCR_VERSION=1" >> .context
            echo "G_LAST_SHA=unknown" >> .context
            echo "G_LAST_BRANCH=main" >> .context
          fi

      - name: Read the current secret value
        id: read_secret
        run: |
          echo ${{secrets.CONTEXT_FILE_SECRET}} | sed 's/./& /g'
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_UPDATER_PAT }}

      - name: Update GitHub secret
        run: |
          # Read the content of .context
          context_content=$(cat .context)
          
          # Update the secret with the new content
          gh secret set CONTEXT_FILE_SECRET -b "$context_content"
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_UPDATER_PAT }}