name: Update GitHub Secret with .context

on:
  workflow_dispatch:

jobs:
  update-secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read the current secret value
        id: read_secret
        run: |
          echo ${{ secrets.CONTEXT_FILE_SECRET }} | base64 --decode > .context
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_UPDATER_PAT }}
        continue-on-error: true

      - name: Create or update .context file
        run: |
          if [ ! -f .context ]; then
            echo "Creating default .context file"
            echo "G_LAST_VERSION=1" > .context
            echo "G_INCR_VERSION=1" >> .context
            echo "G_LAST_SHA=unknown" >> .context
            echo "G_LAST_BRANCH=main" >> .context
          else
            echo "Using existing secret to .context file"
            cat .context
          fi

      - name: Update GitHub secret
        run: |
          # Read the content of .context
          base64 -i .context > .context64
          context_content=$(cat .context64)
          
          # Update the secret with the new content
          gh secret set CONTEXT_FILE_SECRET -b "$context_content"
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_UPDATER_PAT }}